
name: ci

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Shorten commit ID
        shell: bash
        run: |
          echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"

      - name: Checkout
        uses: actions/checkout@v4

      # Optional sanity check (will show *** for secrets)
      - name: Debug contexts (masked in logs)
        run: |
          echo "vars.DOCKERHUB_USERNAME=[${{ vars.DOCKERHUB_USERNAME }}]"
          echo "secrets.DOCKERHUB_TOKEN=[${{ secrets.DOCKERHUB_TOKEN }}]"
          echo "env.COMMIT_ID=[${{ env.COMMIT_ID }}]"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}   # e.g., kobia123
          password: ${{ secrets.DOCKERHUB_TOKEN }}   # Docker Hub PAT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            kobia123/python-app:latest
            kobia123/python-app:${{ env.COMMIT_ID }}
